#
# (C) Copyright 2012 Henrik Nordstrom <henrik@henriknordstrom.net>
#
# Based on some other board Makefile
#
# (C) Copyright 2000-2003
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#
obj-y	+= board.o
obj-$(CONFIG_A10_OLINUXINO_L)	+= dram_a10_olinuxino_l.o
obj-$(CONFIG_A10S_OLINUXINO_M)	+= dram_a10s_olinuxino_m.o
obj-$(CONFIG_CUBIETRUCK)	+= dram_cubietruck.o
